package(default_visibility = ["//dankerer:internal"])

cc_library(
    name = "ui",
    srcs = [
        "imgui_draw.cpp",
        "imgui_widgets.cpp",
    ],
    hdrs = [
        "imconfig.h",
        "imgui.h",
        "imgui_internal.h",
        "imstb_rectpack.h",
        "imstb_textedit.h",
        "imstb_truetype.h",
    ],
)
