package(default_visibility = ["//dankerer:internal"])

cc_library(
    name = "gfx",
    srcs = [
        "camera.cpp",
        "elementBuffer.cpp",
        "framebuffer.cpp",
        "material.cpp",
        "mesh.cpp",
        "renderer.cpp",
        "shader.cpp",
        "shaderProgram.cpp",
        "texture.cpp",
        "uniformBuffer.cpp",
        "vertexArrayConfig.cpp",
        "vertexBuffer.cpp",
    ],
    hdrs = [
        "camera.h",
        "common.h",
        "elementBuffer.h",
        "framebuffer.h",
        "material.h",
        "mesh.h",
        "renderer.h",
        "shader.h",
        "shaderProgram.h",
        "texture.h",
        "uniformBuffer.h",
        "vertexArrayConfig.h",
        "vertexBuffer.h",
    ],
    deps = [
        "//dankerer/base",
    ],
)
