package(default_visibility = ["//dankerer:internal"])

cc_library(
    name = "base",
    srcs = [
        "tinyxml2.cpp",
    ],
    hdrs = [
        "stb_image.h",
        "tiny_obj_loader.h",
        "tinyxml2.h",
    ],
)
