package(default_visibility = ["//dankerer:internal"])

cc_library(
    name = "base",
    srcs = [
        "timer.cpp",
        "tinyxml2.cpp",
    ],
    hdrs = [
        "stb_image.h",
        "timer.h",
        "short_alloc.h",
        "tinyxml2.h",
    ],
)
